#!/usr/bin/env bash

export LIBGUESTFS_BACKEND=direct

virt-builder fedora-38 \
  --format qcow2 \
  --root-password password:fedora \
  --install cloud-init,podman,socat \
  --run /root/scripts/customize-vm \
  #--firstboot /root/scripts/first-boot \
  --output /output/quarkus-dev-vm.qcow2 \
  -v